/**
 * Created by Administrator on 2016/12/16.
 */
myapp.controller("add-attCtrl",function($scope){
    $scope.selectedProvince="";
    $scope.City="";
    $scope.data=[
        {province:"河南省",cities:["郑州市","洛阳市","开封市"]},
        {province:"河北省",cities:["石家庄市","邢台市","唐山市"]},
        {province:"四川省",cities:["成都市","绵阳市","乐山市"]}
    ];
    $scope.Bank="";
    $scope.bankdata=[
        {bank:"中国工商银行"},
        {bank:"中国农业银行"},
        {bank:"中国银行"},
        {bank:"中国建设银行"},
        {bank:"交通银行"},
        {bank:"中信银行"},
        {bank:"中国民生银行"},
        {bank:"中国光大银行"},
        {bank:"华夏银行"},
        {bank:"广东发展银行"},
        {bank:"深圳发展银行"},
        {bank:"招商银行"},
        {bank:"兴业银行"},
        {bank:"上海浦东发展银行"},
        {bank:"中国邮政储蓄银行"}
    ]
});
